import pty, os, time, struct, fcntl, termios
pid, fd = pty.fork()
if pid == 0:
    os.execvp("bash", ["bash", "--norc"])
time.sleep(0.1)
os.write(fd, b"echo line1\n")
time.sleep(0.1)
os.write(fd, b"echo line2\n")
time.sleep(0.1)
os.write(fd, b"echo line3\n")
time.sleep(0.1)
os.write(fd, b"123456789012345")
time.sleep(0.1)
winsize = struct.pack("HHHH", 10, 10, 0, 0)
fcntl.ioctl(fd, termios.TIOCSWINSZ, winsize)
time.sleep(0.1)
winsize = struct.pack("HHHH", 10, 20, 0, 0)
fcntl.ioctl(fd, termios.TIOCSWINSZ, winsize)
time.sleep(0.1)
os.write(fd, b"\n")
time.sleep(0.1)
res = os.read(fd, 4096)
print(repr(res[-200:]))
